# Generated by Django 3.0.5 on 2020-04-11 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skill_id', models.IntegerField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=50, unique=True)),
                ('user_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SkillMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillmap_level', models.IntegerField()),
                ('skillmap_skill_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.Skills')),
                ('skillmap_user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.Users')),
            ],
        ),
    ]
