# Generated by Django 3.0.5 on 2020-04-13 02:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20200411_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 13, 2, 59, 53, 3229)),
        ),
    ]
