# Generated by Django 3.0.5 on 2020-04-16 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_users_user_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='skill_date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 1, 22, 38, 292495)),
        ),
        migrations.AddField(
            model_name='skills',
            name='skill_description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 1, 22, 38, 291495)),
        ),
    ]
