# Generated by Django 3.0.5 on 2020-04-16 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20200415_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill_date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 3, 38, 4, 340758)),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 3, 38, 4, 340758)),
        ),
        migrations.AlterUniqueTogether(
            name='skillmap',
            unique_together={('skillmap_user_id', 'skillmap_skill_id')},
        ),
    ]
