# Generated by Django 3.0.5 on 2020-04-17 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20200415_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill_date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 7, 14, 9, 168845)),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 7, 14, 9, 167845)),
        ),
    ]
